#development specific settings

production:
  PORT: 3001
  SERVER_URL: http://localhost
  SERVER_PORT: 9001
  CLINT_URL: localhost
  TOKEN_NAME: "hack-xxx-comet-assn"
  DEBUG: false


development:
  PORT: 3001
  SERVER_URL: http://localhost
  SERVER_PORT: 9001
  CLINT_URL: localhost
  TOKEN_NAME: "hack-xxx-comet-assn"
  DEBUG: false